import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { toast } from 'react-toastify';
import { FileText, Calendar, Download, Eye } from 'lucide-react';
import { jsPDF } from 'jspdf';
import { API_URL } from '../../../api';
import TopNavbar from './TopNavbar';

const PatientImmunizationLogs = () => {
  const [logs, setLogs] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedLog, setSelectedLog] = useState(null);

  const token = localStorage.getItem('token');

  useEffect(() => {
    fetchLogs();
  }, []);

  const fetchLogs = async () => {
    try {
      const res = await axios.get(`${API_URL}/api/V1/logs`, {
        headers: { Authorization: `Bearer ${token}` }
      });

      // Supports either direct array response or wrapped payloads
      const payload = Array.isArray(res.data)
        ? res.data
        : Array.isArray(res.data?.data)
          ? res.data.data
          : [];

      setLogs(payload);
    } catch (err) {
      toast.error('Failed to load immunization logs');
    } finally {
      setLoading(false);
    }
  };

  const handleView = (log) => setSelectedLog(log);

  const handleDownloadCertificate = (log) => {
    try {
      // If backend provides a direct certificate URL/base64, use it first
      if (log?.digitalCertificate) {
        const link = document.createElement('a');
        link.href = log.digitalCertificate;
        link.download = `immunization-certificate-${log._id}.pdf`;
        link.target = '_blank';
        link.rel = 'noopener noreferrer';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        return;
      }

      // Fallback: generate downloadable PDF certificate from log details
      const doc = new jsPDF({ unit: 'pt', format: 'a4' });

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(20);
      doc.text('Immunization Certificate', 50, 70);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(12);
      doc.text('Generated by UniVax', 50, 92);

      const lines = [
        `Vaccine: ${log?.vaccineId?.name || 'N/A'}`,
        `Brand: ${log?.brand || 'N/A'}`,
        `Batch Number: ${log?.batchNumber || 'N/A'}`,
        `Dose Number: ${log?.doseNumber || 'N/A'}`,
        `Date Administered: ${new Date(log?.dateAdministered).toLocaleDateString()}`,
        `Clinic: ${log?.clinic || 'N/A'}`,
        `Notes: ${log?.notes || 'No additional notes'}`,
        `Certificate ID: ${log?._id || 'N/A'}`,
      ];

      let y = 130;
      lines.forEach((line) => {
        const wrapped = doc.splitTextToSize(line, 500);
        doc.text(wrapped, 50, y);
        y += wrapped.length * 18;
      });

      doc.save(`immunization-certificate-${log?._id || 'record'}.pdf`);
      toast.success('Certificate downloaded');
    } catch (error) {
      console.error(error);
      toast.error('Failed to download certificate');
    }
  };

  return (
    <>
      <TopNavbar />

      <div className="min-h-screen bg-gradient-to-br from-blue-50 via-sky-50 to-cyan-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          {loading ? (
            <div className="text-center py-16">
              <div className="text-teal-600">Loading your vaccination records...</div>
            </div>
          ) : (
            <>
              {/* Updated Header - Blue gradient like Appointments page */}
              <div className="mb-8">
                <h1 className="text-4xl font-bold bg-gradient-to-r from-blue-600 to-cyan-600 bg-clip-text text-transparent">
                  Immunization Logs
                </h1>
                <p className="text-gray-600 mt-2">Complete record of all your vaccinations with brand & batch details</p>
              </div>

              {/* Logs Grid */}
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {logs.length === 0 ? (
                  <div className="col-span-3 text-center py-16 bg-white rounded-3xl shadow-sm">
                    <FileText size={64} className="mx-auto text-gray-300 mb-4" />
                    <p className="text-gray-500">No immunization records yet</p>
                  </div>
                ) : (
                  logs.map((log) => (
                    <div key={log._id} className="bg-white rounded-3xl shadow-sm border border-gray-100 p-6 hover:shadow-xl transition-all">
                      <div className="flex justify-between items-start mb-4">
                        <div>
                          <p className="text-lg font-semibold text-gray-800">{log.vaccineId?.name || 'Vaccine'}</p>
                          <p className="text-sm text-teal-600">{log.brand} • Batch {log.batchNumber}</p>
                        </div>
                        <span className="px-3 py-1 bg-teal-100 text-teal-700 text-xs font-medium rounded-2xl">
                          Dose {log.doseNumber}
                        </span>
                      </div>

                      <div className="flex items-center gap-2 text-gray-500 text-sm mb-4">
                        <Calendar size={16} />
                        {new Date(log.dateAdministered).toLocaleDateString('en-US', { 
                          year: 'numeric', 
                          month: 'long', 
                          day: 'numeric' 
                        })}
                      </div>

                      <p className="text-gray-600 text-sm mb-6 line-clamp-2">{log.clinic}</p>

                      <button
                        onClick={() => handleView(log)}
                        className="w-full flex items-center justify-center gap-2 py-3 bg-teal-600 hover:bg-teal-700 text-white rounded-2xl transition-colors"
                      >
                        <Eye size={18} />
                        View Full Record + Certificate
                      </button>
                    </div>
                  ))
                )}
              </div>

              {/* Detail Modal */}
              {selectedLog && (
                <div className="fixed inset-0 bg-black/60 flex items-center justify-center z-50">
                  <div className="bg-white rounded-3xl max-w-lg w-full mx-4 p-8">
                    <h2 className="text-2xl font-bold mb-6">Vaccination Record</h2>
                    <div className="space-y-6 text-sm">
                      <div className="flex justify-between">
                        <span className="text-gray-500">Date</span>
                        <span className="font-medium">{new Date(selectedLog.dateAdministered).toLocaleDateString()}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-gray-500">Brand</span>
                        <span className="font-medium">{selectedLog.brand}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-gray-500">Batch Number</span>
                        <span className="font-medium">{selectedLog.batchNumber}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-gray-500">Clinic</span>
                        <span className="font-medium">{selectedLog.clinic}</span>
                      </div>
                      <div>
                        <span className="text-gray-500 block mb-1">Notes</span>
                        <p className="text-gray-700">{selectedLog.notes || 'No additional notes'}</p>
                      </div>
                    </div>

                    <div className="flex gap-3 mt-10">
                      <button onClick={() => setSelectedLog(null)} className="flex-1 py-4 border border-gray-300 rounded-2xl font-medium">Close</button>
                      <button
                        onClick={() => handleDownloadCertificate(selectedLog)}
                        className="flex-1 py-4 bg-teal-600 text-white rounded-2xl font-medium flex items-center justify-center gap-2"
                      >
                        <Download size={20} /> Download Certificate
                      </button>
                    </div>
                  </div>
                </div>
              )}
            </>
          )}
        </div>
      </div>
    </>
  );
};

export default PatientImmunizationLogs;